### ISSUE TITLE
[Feature Request] Add holograms

### ISSUE THREAD

**Issue by SnowCutieOwO** [pigaut/Orestack#1]
Blocks that could be gathered would show some lines of holograms, like its name and regenerate count down, and some extra information
~Just like the WynnCraft one~

**Comment by pigaut** [comment]
Sure, I'll see what I can do, I'm thinking of something like this:
```
hologram:
  offset: { x: 0, y: 1, z: 0 }
  title: '%Generator% Generator' 
  subtitle:
    - '[][][][][][][][][][]'
    - '[][][][][][][][]'
    - '[][][][][][]'
    - '[][][][]'
    - '[][]'
```

**Comment by SnowCutieOwO** [comment]
> Sure, I'll see what I can do, I'm thinking of something like this:
> 
> ```
> hologram:
>   offset: { x: 0, y: 1, z: 0 }
>   title: '%Generator% Generator' 
>   subtitle:
>     - '[][][][][][][][][][]'
>     - '[][][][][][][][]'
>     - '[][][][][][]'
>     - '[][][][]'
>     - '[][]'
> ```

Pretty! Maybe you could add two different holograms for different state, like `ready` and `preparing` section:

``` YAML
hologram:
  ready:
    offset: ...
    title: "Wheat &7(Ripe)"
    subtitle:
      - "Duration: 5s"
  preparing:
    offset: ...
    title: "Wheat &7(Growing)"
    subtitle:
      - "Time left: {time}"
```
