### ISSUE TITLE
[Feature Request] add support for structures & condition suggestion

### ISSUE THREAD

**Issue by SnowCutieOwO** [pigaut/Orestack#2]
I mean like trees, you could use two different state to make them could be gained by plugin
~~Yes, also like the WynnCraft :P~~

Condition suggestion:

``` YAML
...
  ready:
  - condition: "%placeholder% == something" # just add placeholder compare :3
    action:
       - 'give: {item-name} {amount}' # and there you go, you could work on item plugin hook, but a bit tire though :3
       - 'command: {as-who?} {content}' # could be 'console', 'player' or 'op', example: "command: op /say hello!" will run `/say hello!` in operator's identity
       - 'tell: {to-who?} {content}' # could be player name, or 'self', example: 'tell: self You started picking the crops...' will tell player himself the message
```

**Comment by pigaut** [comment]
Added multi block generators to the planned features on plugin page.
I'll add placeholder conditions once i'm done with holograms.
What you have in the actions can be done like this:
```
actions:
  - [give item, item_name:64]   # Give 64 of an item from /items/ folder
  - [command, say hello]   # you can also use: op_command and console_command
  - [chat message, 'You started picking the crops']
```
More info at wiki (work in progress): https://github.com/pigaut/Orestack/wiki/Configuration

**Comment by pigaut** [comment]
'is_placeholder' condition added in 3.14 (read changelog for changes to database)
How to use it:
```
on-click:
  if:
    - condition: is placeholder
      placeholder: '%generator_stage%'   # Internal or placeholderApi placeholder (haven't tested placeholderApi but it should work)
      amount: 1-5

    - condition: is placeholder
      placeholder: %generator% 
      value: 'example_name'

# In short format (preferred)
on-click:
  if:
    - [ is placeholder, "%generator_stage%", 1-5 ]   # Check if the generator is in stage 1 to 5
```

Regarding multi block generators (structures), that will probably become a premium only feature.
The plugin will be split in two versions, even though I don't like (because it's more work lol) it is the only way to make people purchase premium.

I am currently giving away 10 free copies of the premium version to the first 10 users who join my discord and give me their spigotMC username. I feel like you should get one since you also suggested the idea.
